export const tracks = [
  {
    title: "Swarm-Enabled Clinical Diagnostics & Autonomous Image Analysis",
    short: "Clinical Diagnostics",
    partner: "OpenSwarm",
    problem: "Radiologists and pathologists evaluate tens of thousands of images under immense time pressure. Gigabyte-scale fMRI scans and whole-slide histology can hide early anomalies, while traditional AI flags a region without explaining why.",
    objective: "Use AI agents to analyze medical images, find anomalies, and draft evidence-backed reports for clinician review.",
    ideas: ["Coordinate agents across image preparation, anomaly review, and literature search.", "Build a report with traceable evidence and uncertainty for clinician review."],
    detail: "OpenSwarm: build the agent layer on their desktop orchestrator.",
  },
  {
    title: "AI for Clinical Research & Trial Operations",
    short: "Clinical Research & Trials",
    partner: "Harbor",
    problem: "Startups often outsource clinical studies to CROs, paying for slow, manual, error-prone processes. Protocol amendments create rework, data quality can disappoint, and lean teams lack a real-time view of their trial.",
    objective: "Help small teams run better clinical studies with automated data capture, risk monitoring, or patient support. Design for audit trails, e-signatures, and version control.",
    ideas: ["Flag study-data inconsistencies and surface monitoring risks.", "Track protocol changes with a reviewable version history.", "Prototype a patient-facing visit and follow-up companion."],
    detail: "Harbor workshop before ideation. Design constraints: GCP and 21 CFR Part 11; prototypes are not compliance-certified.",
  },
  {
    title: "Personalized Medicine: From Intake to Approved Formulation",
    short: "Personalized Medicine",
    partner: "CLD-9",
    problem: "Robotic compounding makes individualized doses economically viable, but deciding, justifying, and documenting a formulation remains a bottleneck. Today that process runs through a pharmacist, questionnaires, spreadsheets, and memory.",
    objective: "Turn patient intake into a traceable candidate formulation for professional review, or build a digital batch record. Flag interactions, contraindications, and dose limits.",
    ideas: ["Connect synthetic intake data to a reviewable formulation rationale.", "Prototype interaction and dose-ceiling alerts with evidence links.", "Build a digital batch-record review interface."],
    detail: "CLD-9: explore what the Nexus platform consumes and produces, with Khushang judging.",
  },
  {
    title: "Open Problem Challenge",
    short: "Open Problem Challenge",
    partner: "Bring your own problem",
    problem: "Already building in life sciences, or found a problem the other tracks do not cover? Bring it here: healthcare delivery, biotech tooling, diagnostics, lab operations, or patient access.",
    objective: "Solve a life-sciences problem outside the other tracks: healthcare delivery, biotech, lab operations, or patient access.",
    ideas: ["Remove a repetitive bottleneck in a research lab.", "Help patients navigate an access barrier.", "Bring an existing life-sciences project and make meaningful progress."],
    detail: "Existing projects welcome.",
  },
];
