export const tracks = [
  {
    title: "Swarm-Enabled (Optional) Clinical Diagnostics & Autonomous Image Analysis",
    short: "See more. Explain why.",
    partner: "OpenSwarm",
    problem: "Radiologists and pathologists evaluate tens of thousands of medical images a year under immense time pressure. An fMRI scan or whole-slide histology image can be gigabytes, and finding early-stage anomalies, such as micro-metastases or subtle tissue degradation, is like finding a needle in a haystack. Traditional AI tools flag a region of interest and leave the clinician to figure out the why.",
    objective: "Move beyond single-function classifiers to an agentic diagnostic workflow. Build multi-agent systems that pre-process heavy imagery, identify anomalies, cross-reference medical literature for differential diagnoses, and autonomously draft a clinician-ready report explaining their reasoning.",
    ideas: ["Coordinate agents across image preparation, anomaly review, and literature search.", "Build a report with traceable evidence and uncertainty for clinician review."],
    detail: "OpenSwarm: build the agent layer on their desktop orchestrator. Using OpenSwarm is optional, including in this track.",
  },
  {
    title: "AI for Clinical Research & Trial Operations",
    short: "Less paperwork. Better research.",
    partner: "Harbor",
    problem: "Most startups outsource clinical studies to CROs, paying heavily for processes that are slow, manual, and error-prone. A single protocol amendment can mean weeks of rework, the data that comes back is often lower quality than the price tag suggests, and lean teams have no real-time view into their own trial.",
    objective: "Build tools that let a small team run a rigorous study themselves. AI-assisted protocol and study builds, automated source data capture, anomaly detection across incoming site data, monitoring that surfaces risk before a site visit would, or patient-facing interfaces that cut dropout. Compliance is a design constraint, not an afterthought: GCP and 21 CFR Part 11 mean audit trails, e-signatures, and version control on everything.",
    ideas: ["Flag study-data inconsistencies and surface monitoring risks.", "Track protocol changes with a reviewable version history.", "Prototype a patient-facing visit and follow-up companion."],
    detail: "Harbor: compliant EDC domain expertise, with a workshop before ideation opens. Track brief references GCP and 21 CFR Part 11; a prototype is not a compliance certification.",
  },
  {
    title: "Personalized Medicine: From Intake to Approved Formulation",
    short: "Make every decision traceable.",
    partner: "CLD-9",
    problem: "Robotic compounding makes an n-of-1 dose economically viable for the first time. The bottleneck has moved upstream: a machine can execute a formulation far faster than a human can decide what belongs in it, justify that decision, and document it to a standard a quality unit will sign off on. Today that path runs through a pharmacist, a questionnaire, a spreadsheet, and memory.",
    objective: "Build the layer that produces a defensible formulation. Turn intake data, including labs, medication lists, wearables, and questionnaires, into a candidate formulation with explicit rationale. Check interactions, contraindications, and cumulative dose ceilings across everything the patient already takes. Generate the record that makes the decision auditable. Or work the downstream end: what a pharmacy or telehealth partner needs to see in a digital batch record before releasing a dose.",
    ideas: ["Connect synthetic intake data to a reviewable formulation rationale.", "Prototype interaction and dose-ceiling alerts with evidence links.", "Build a digital batch-record review interface."],
    detail: "CLD-9: explore what the Nexus platform consumes and produces, with Khushang judging.",
  },
  {
    title: "Open Problem Challenge related to Medicine and Technology",
    short: "Your problem. A working build.",
    partner: "Bring your own problem",
    problem: "Bring your own problem. If you're already building something in life sciences, or you've found a problem the other tracks don't cover, this is your track. Healthcare delivery, biotech tooling, diagnostics, lab operations, patient access: anything where a working build can move the problem forward.",
    objective: "Deliver a working prototype by Sunday, not a pitch for one. Teams are judged on the strength of the problem, evidence of validation with someone who has it, and how far the build actually got.",
    ideas: ["Remove a repetitive bottleneck in a research lab.", "Help patients navigate an access barrier.", "Bring an existing life-sciences project and make meaningful progress."],
    detail: "The same working-prototype standard applies across all four tracks.",
  },
];
